export { default as image1 } from './1.png';
export { default as image2 } from './2.png';
export { default as image3 } from './3.jpg';
export { default as image4 } from './4.jpeg';
export { default as image5 } from './5.png';
export { default as image6 } from './6.jpg';
export { default as image7 } from './7.jpg';
export { default as image8 } from './8.png';
export { default as image9 } from './9.jpg';